name: scrollable_list_tab_scroller
description:  Customizable Flutter widget which synchronize a scrollable grouped items list with tabs
version: 1.1.0

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

repository: https://github.com/railson-ferreira/scrollable_list_tab_scroller

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.5
  easy_debounce: ^2.0.1
  uuid: ^3.0.5
  # FIXME: Once https://github.com/optimist-dev/scrolls_to_top/pull/12 is merged, we can go back to
  #   use the official package from pub with a newer version.
  scrolls_to_top:
    git:
      url: https://github.com/changweihua/scrolls_to_top.git
      ref: 5d15e145734a375f6deb717e65a6aa3220da7545

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
